# Jekyll _config.yml
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NTPsec Project Blog
email: contact@ntpsec.org
description: > # this means to ignore newlines until "baseurl:"
  The blog for the NTPsec Project.
  NTPsec is a secure, hardened, and improved implementation of Network
  Time Protocol derived from NTP Classic, Dr. David Millsâ€™s original.
  Our goal is to deliver code that can be used with confidence in
  deployments with the most stringent security, availability, and
  assurance requirements.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ntpsec.org" # the base hostname & protocol for your site
twitter_username: ntpsec
github_username:  ntpsec

# Build settings
markdown: kramdown
exclude: ["README.md"]

# asciidoc stuff
asciidoc:
  processor: asciidoctor
  ext: asciidoc,adoc,ad

asciidoctor: {}

plugins:
  - jekyll-asciidoc
whitelist:
  - jekyll-asciidoc
